# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Hover Documentation
email: admin@usehover.com
description: > # this means to ignore newlines until "baseurl:"
  Hover makes mobile money easy for app developers
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://docs.usehover.com" # the base hostname & protocol for your site
twitter_username: usehover
github_username: UseHover
permalink: pretty

# Build settings
markdown: kramdown
